### ISSUE TITLE
Dataset as Test set

### ISSUE THREAD

**Issue by willycornelissen** [CPJKU/onset_db#2]
Hello Mr. Bock!

Sometime ago, you shared with me a dataset for onset detection with 321 files and more than 27.000 onsets noted. I am using it on my dissertation and I would like to use it with Madmom onset detection method (madmom.features.onset.CNNOnsetProcessor).

Did you use this dataset to train the model  of onset detection in model?
If you used, I could not use it as test dataset?

**Comment by superbock** [comment]
Yes, this dataset was used for training in an 8-fold cross validation manner, i.e. in each fold 1/8 of the data was used for testing, 1/8 for validation and the remaining 6/8 for training.
